BudgetPlanner/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BudgetPlanner.Data;
using BudgetPlanner.Models;
using Microsoft.AspNetCore.Identity;
using BudgetPlanner.Persistence.Interfaces;
using Autofac;
using BudgetPlanner.Persistence;
using BudgetPlanner.Persistence.Repositories;

namespace BudgetPlanner.Controllers
{
    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public static ActionResult ReturnUrl { get; set; }
        private static IContainer container { get; set; }

        public CompanyController(IUnitOfWork unitOfWork)
        {
            //var builder = new ContainerBuilder();
            //builder.RegisterType<UnitOfWork>().As<IUnitOfWork>();
            //builder.Register(c => new UnitOfWork()).As<IUnitOfWork>();
            //container = builder.Build();
            //using (var scope = container.BeginLifetimeScope())
            //    var blah = scope.Resolve<IUnitOfWork>();
            _unitOfWork = unitOfWork;
        }

        // GET: Company
        public async Task<IActionResult> Index()
        {
            var user = await _unitOfWork.Users.GetCurrentUserAsync(User);
            if (user != null)
            {
                var model = await _unitOfWork.Companies.GetAllAsync();
                TransactionController.ReturnUrl = RedirectToAction(nameof(Index));
                SubscriptionController.ReturnUrl = RedirectToAction(nameof(Index));
                ReturnUrl = RedirectToAction(nameof(Index));
                ViewData["balance"] = user.Balance;
                return View(model);
            } 
            return RedirectToAction("Login", "Identity/Account");
        }


        public async Task<IActionResult> IndexSearch(string search)
        {
            var user = await _unitOfWork.Users.GetCurrentUserAsync(User);
            if (search == null)
            {
                search = "";
            }
            if (user != null)
            {
                var model = await _unitOfWork.Companies.FirstAsync(c => c.CompanyName.Contains(search));
                TransactionController.ReturnUrl = RedirectToAction(nameof(Index));
                SubscriptionController.ReturnUrl = RedirectToAction(nameof(Index));
                ReturnUrl = RedirectToAction(nameof(Index));

                ViewData["balance"] = user.Balance;
                return View("Index", model);
            }
            return RedirectToAction("Login", "Identity/Account");
        }


        public IActionResult Return()
        {
            return ReturnUrl;
        }

        // GET: Company/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var company = await _unitOfWork.Companies.FirstInclTransSubAsync(c => c.CompanyId == id.Value);
            if (company == null)
            {
                return NotFound();
            }
            TransactionController.ReturnUrl = RedirectToAction(nameof(Index));
            SubscriptionController.ReturnUrl = RedirectToAction(nameof(Index));
            ReturnUrl = RedirectToAction(nameof(Index));
            return View(company);
        }

        // GET: Company/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Company/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CompanyId,CompanyName")] Company company)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Companies.AddAsync(company);
                await _unitOfWork.CompleteAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(company);
        }

        // GET: Company/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var company = await _unitOfWork.Companies.GetAsync(id.Value);
            if (company == null)
            {
                return NotFound();
            }
            return View(company);
        }

        // POST: Company/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CompanyId,CompanyName")] Company company)
        {
            if (id != company.CompanyId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _unitOfWork.Companies.AddAsync(company);
                    await _unitOfWork.CompleteAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompanyExists(company.CompanyId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(company);
        }

        // GET: Company/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var company = await _unitOfWork.Companies.GetAsync(id.Value);
            if (company == null)
            {
                return NotFound();
            }

            return View(company);
        }

        // POST: Company/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var company = await _unitOfWork.Companies.GetAsync(id);
            _unitOfWork.Companies.Remove(company);
            await _unitOfWork.CompleteAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CompanyExists(int id)
        {
            return _unitOfWork.Companies.Any(e => e.CompanyId == id);
        }
    }
}

BudgetPlanner/Controllers/SubscriptionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BudgetPlanner.Data;
using BudgetPlanner.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.SignalR;
using BudgetPlanner.Persistence.Interfaces;

namespace BudgetPlanner.Controllers
{
    public class SubscriptionController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public static ActionResult ReturnUrl { get; set; }

        public SubscriptionController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        

        // GET: Subscription
        public async Task<IActionResult> Index()
        {
            var user = await _unitOfWork.Users.GetCurrentUserAsync(User);
            if (user != null)
            {
                var model = await _unitOfWork.Subscriptions
                    .WhereDescendingInclCompanyAsync(s => s.UserId == user.Id);
                TransactionController.ReturnUrl = RedirectToAction(nameof(Index));
                CompanyController.ReturnUrl = RedirectToAction(nameof(Index));
                ReturnUrl = RedirectToAction(nameof(Index));

                ViewBag.UserId = user.Id;
                ViewData["balance"] = user.Balance;
                return View(model);
            }
            return RedirectToAction("Login", "Identity/Account");
        }
        

        public async Task<IActionResult> IndexSearch(string search)
        {
            var user = await _unitOfWork.Users.GetCurrentUserAsync(User);
            if (search == null)
            {
                search = "";
            }
            if (user != null) 
            {
                var model = await _unitOfWork.Subscriptions
                    .WhereDescendingInclCompanyAsync(s => s.UserId == user.Id && s.SubscriptionName.Contains(search));
                TransactionController.ReturnUrl = RedirectToAction(nameof(Index));
                CompanyController.ReturnUrl = RedirectToAction(nameof(Index));
                ReturnUrl = RedirectToAction(nameof(Index));
                
                ViewBag.UserId = user.Id;
                ViewData["balance"] = user.Balance;
                return View("Index", model);
            }
            return RedirectToAction("Login", "Identity/Account");
        }


        public IActionResult Return()
        {
            return ReturnUrl;
        }


        public async Task<IActionResult> Update(int id)
        {
            var sub = await _unitOfWork.Subscriptions.FirstInclCompanyAsync(s => s.SubscriptionId== id);
            var user = await _unitOfWork.Users.GetCurrentUserAsync(User);

            var company = _unitOfWork.Companies.FirstInclTrans(c => c.CompanyId == sub.CompanyId);
            _unitOfWork.AddPayment(sub, user, company);
            _unitOfWork.Complete();

            return ReturnUrl;
        }


        // GET: Subscription/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subscription = await _unitOfWork.Subscriptions
                .FirstInclTransCompanyAsync(m => m.SubscriptionId == id);
            if (subscription == null)
            {
                return NotFound();
            }
            decimal temp = (decimal)0.00;
            try
            {
                temp = (subscription.Progress / subscription.Target.Value)*100;
            }
            catch { }   
            ViewData["progress"] = temp;
            TransactionController.ReturnUrl = RedirectToAction(nameof(Details));
            ReturnUrl = RedirectToAction(nameof(Details));
            return View(subscription);
        }

        // GET: Subscription/Create
        [HttpGet("/Subscription/Create/deposit")]
        public IActionResult Create(bool deposit)
        {
            var model = CreateInit(deposit);
            return View(model);
        }

        public SubCreate CreateInit(bool deposit)
        {
            var companies = _unitOfWork.Companies.GetAllAsNoTracking();
            var output = new SubCreate
            {
                Companies = new SelectList(companies, "CompanyId", "CompanyName"),
                InOut = deposit

            };

            return output;
        }

        // POST: Subscription/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SubCreate sub)
        {
            if (ModelState.IsValid && sub.Amount != 0)
            {
            var user = await _unitOfWork.Users.GetCurrentUserAsync(User);
                var company = await _unitOfWork.Companies.GetAsync(sub.CompanyId);
                Subscription subscription = new Subscription { };
                subscription.Amount = (decimal)10.00;
                subscription = PostCreate(sub, subscription, user, company);
                
                _unitOfWork.Subscriptions.AddAsync(subscription);
                _unitOfWork.Complete();
                return ReturnUrl;
            }
            return RedirectToAction(nameof(Create));
        }

        public Subscription PostCreate(SubCreate sub, Subscription subscription, User user, Company company)
        {
            DateTime lastDue = sub.StartDate;

            decimal amount = sub.Amount;
            decimal target = (decimal)0.00;
            try { target = sub.Target.Value; }
            catch { }

            if ((sub.InOut && sub.Amount < 0) || (!sub.InOut && sub.Amount > 0))
            {
                amount = (-1)*amount;
                try { target = (-1)*target; }
                catch { }
            }

            subscription.SubscriptionName = sub.SubscriptionName;
            subscription.Company = company;
            subscription.CompanyId = company.CompanyId;
            subscription.Amount = amount;
            subscription.Target = target;
            subscription.Transactions = sub.Transactions;
            subscription.User = user;
            subscription.UserId = user.Id;
            subscription.InOut = sub.InOut;
            subscription.Interval = sub.Interval;
            subscription.NextDue = sub.StartDate;
            
            return subscription;
        }

        // GET: Subscription/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var sub = await _unitOfWork.Subscriptions.GetAsync(id.Value);

            var amount = sub.Amount;
            var target = sub.Target.Value;
            if (amount < 0)
            {
                target = target * (-1);
                amount = amount * (-1);
            }
            string interval = sub.Interval;
            SubCreate subscription = new SubCreate
            {
                Amount = amount,
                Target = target,
                SubscriptionName = sub.SubscriptionName,
                StartDate = sub.NextDue,
                CompanyId = sub.CompanyId,
                InOut = sub.InOut,
                Interval = interval
            };

            ViewData["id"] = id;
            if (subscription == null)
            {
                return NotFound();
            }
            return View(subscription);
        }

        // POST: Subscription/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, SubCreate sub)
        {
            var subscription = await _unitOfWork.Subscriptions.GetAsync(id);
            if (ModelState.IsValid && sub.Amount != 0)
            {
                try
                {
            var user = await _unitOfWork.Users.GetCurrentUserAsync(User);
                    var company = await _unitOfWork.Companies.GetAsync(sub.CompanyId);
                    subscription = PostCreate(sub, subscription, user, company);
                    _unitOfWork.Subscriptions.Update(subscription);
                    _unitOfWork.Complete();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SubscriptionExists(subscription.SubscriptionId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return ReturnUrl;
            }
            return View(sub);
        }

        // GET: Subscription/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subscription = await _unitOfWork.Subscriptions
                .FirstAsync(m => m.SubscriptionId == id);
            if (subscription == null)
            {
                return NotFound();
            }

            return View(subscription);
        }

        // POST: Subscription/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var subscription = await _unitOfWork.Subscriptions.GetAsync(id);
            var transactions = await _unitOfWork.Transactions.WhereAsync(t => t.SubId == subscription.SubscriptionId);
            foreach (var trans in transactions) 
            {

BudgetPlanner/Views/Shared/_DueModal.cshtml
<div class="modal fade" id="subDueModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title text-center" id="exampleModalLabel">The Following Subscriptions Are Due</h3>
            </div>
            <div class="modal-body">
                <ul style="list-style:none;" id="subDueModalBody"></ul>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

BudgetPlanner/Views/Shared/_IndexPartial.cshtml
<div class="container">
    <br />
    <br />
    <ul class="list-group list-inline">
        <li>
            <div class="dropdown">
                <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    New Payment
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a asp-controller="Transaction" asp-action="Create" asp-route-subId="0" asp-route-deposit="true" role="button" class="btn dropdown-payment">Deposit</a>
                    <a asp-controller="Transaction" asp-action="Create" asp-route-subId="0" asp-route-deposit="false" role="button" class="btn dropdown-payment">Withdrawal</a>
                </div>
            </div>
        </li>
        <li>
            <div class="dropdown">
                <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    New Subscription
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a asp-controller="Subscription" asp-route-deposit="true" asp-action="Create" role="button" class="btn dropdown-payment">Deposit</a>
                    <a asp-controller="Subscription" asp-route-deposit="false" asp-action="Create" role="button" class="btn dropdown-payment">Withdrawal</a>
                </div>
            </div>
        </li>
        <li><a asp-controller="Company" asp-action="Create" role="button" class="btn btn-primary">New Company</a></li>
        <li>
            @{string search = "";}
            <form class="form-group" method="get">
                <input type="text" class="form-control col-sm-2" style="width:150px;" asp-for="@(search)" />
                <input type="submit" asp-action="IndexSearch" asp-route-search="@(search)" class="form-control btn btn-primary" style="width:100px;" value="Search" />
            </form>
        </li>
        <li class="pull-right" id="balance"><h3>Balance: @ViewData["balance"]</h3></li>
    </ul>
</div>

BudgetPlanner/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BudgetPlanner</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Welcome</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Transaction" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Subscription" asp-action="Index">Subscriptions</a></li>
                    <li><a asp-area="" asp-controller="Company" asp-action="Index">Companies</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        <script src="~/lib/SignalR/signalr.js"></script>
        <script src="~/js/connect.js"></script>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - BudgetPlanner</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>